import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner'
import Card from '../components/card'
import { fetchHalalStores } from '../lib/halal-stores'
import useTrackLocation from '../hooks/use-track-location'
import { useEffect, useContext } from 'react'
import { ACTION_TYPES, StoreContext } from '../store/store-context'

export async function getStaticProps(context) {

  const halalStoresData = await fetchHalalStores();
  return {
    props: {
      halalStoresData,
    },
  };
}

export default function Home(props) {
  const { locationErrorMessage, handleTrackLocation, isFindingLocation } = useTrackLocation();

  
  const { dispatch, state } = useContext(StoreContext);
  const { halalStores, latLong } = state;

  const handleOnBannerBtnClick = () => {
    handleTrackLocation();
  }

  useEffect(() => {
    async function fetchStoresNearBy () {
    if (latLong) {
      try {
        const fetchedHalalStores = await fetchHalalStores(latLong, 30);
        //setFetchedStores(fetchedHalalStores);
        dispatch({
          type: ACTION_TYPES.SET_HALAL_STORES,
          payload: {
            halalStores: fetchedHalalStores
        } 
        })
      }
      catch(error){
        console.log(error);
        //setError
      }
      }
    }
    fetchStoresNearBy();
  }, [latLong])


  return (
    <div className={styles.container}>
      <Head>
        <title>Halal Stores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={isFindingLocation ? 'loading...' : 'View stores nearby'}
          handleOnClick={handleOnBannerBtnClick} />
        {/*      <div className={styles.heroImage}>
          <Image src='/static/hero-image.png' alt='hero image' width={700} height={400} />
        </div> */}
        {locationErrorMessage && <p> Something went wrong: {locationErrorMessage} </p>}

        {halalStores.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}> Stores near me </h2>
            <div className={styles.cardLayout}>
              {halalStores.map(store => {
                return (
                  <Card
                    key={store.id}
                    name={store.name}
                    imgUrl={store.image_url}
                    href={`/halal-store/${store.id}`}
                    className={styles.card}
                  >
                  </Card>
                )
              })
              }
            </div>
          </div>
        )}

      {props.halalStoresData.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}> Berlin Stores </h2>
            <div className={styles.cardLayout}>
              {props.halalStoresData.map(store => {
                return (
                  <Card
                    key={store.id}
                    name={store.name}
                    imgUrl={store.image_url}
                    href={`/halal-store/${store.id}`}
                    className={styles.card}
                  >
                  </Card>
                )
              })
              }
            </div>
          </div>
        )}
      </main>

    </div>
  )
}
