import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner'
import Card from '../components/card'
import { fetchHalalStores } from '../lib/halal-stores'

export async function getStaticProps(context) {
  
  const halalStoresData = await fetchHalalStores();

  return {
    props: {
      halalStoresData,
    },
  };
}

export default function Home(props) {
  const handleOnBannerBtnClick = (e) => {
    e.target.innerHTML = 'Loading ...';
  }

  const halalStores = props.halalStoresData;

  return (
    <div className={styles.container}>
      <Head>
        <title>Halal Stores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText={'View stores nearby'} handleOnClick={handleOnBannerBtnClick} />
        {/*      <div className={styles.heroImage}>
          <Image src='/static/hero-image.png' alt='hero image' width={700} height={400} />
        </div> */}
        {halalStores.length > 0 && <div>
          <h2 className={styles.heading2}> Berlin Stores </h2>
          <div className={styles.cardLayout}>
            {halalStores.map(store => {
              return (
                <Card
                  key={store.fsq_id}
                  name={store.name}
                  imgUrl={store.image_url}
                  href={`/halal-store/${store.fsq_id}`}
                  className={styles.card}
                >
                </Card>
              )
            })
            }


          </div>
        </div>
        }
      </main>

    </div>
  )
}
